In [1]:
from matplotlib import pyplot as plt
from scipy.stats import linregress
import numpy as np
from sklearn import datasets
import pandas as pd

In [2]:
games_df = pd.read_csv('data/nfl-big-data-bowl-2024/games.csv')
games_df = games_df.astype({'gameId': 'string',})
games_df.head()

,gameId,season,week,gameDate,gameTimeEastern,homeTeamAbbr,visitorTeamAbbr,homeFinalScore,visitorFinalScore
0,2022090800,2022,1,09/08/2022,20:20:00,LA,BUF,10,31
1,2022091100,2022,1,09/11/2022,13:00:00,ATL,NO,26,27
2,2022091101,2022,1,09/11/2022,13:00:00,CAR,CLE,24,26
3,2022091102,2022,1,09/11/2022,13:00:00,CHI,SF,19,10
4,2022091103,2022,1,09/11/2022,13:00:00,CIN,PIT,20,23

In [3]:
# Fill non-finite values with 0
games_df['gameId'] = games_df['gameId'].fillna(0)
# Convert the column to integer
games_df['gameId'] = games_df['gameId'].astype(int)

In [4]:
matchups_df = pd.DataFrame({
    'matchup': games_df['homeTeamAbbr'] + '_' + games_df['visitorTeamAbbr'],
    'gameId': games_df['gameId'],
    'week': games_df['week'],
    'home': games_df['homeTeamAbbr'],
    'away': games_df['visitorTeamAbbr'],
    'week': games_df['week']
})
matchups_df.head()

   matchup      gameId  week home away
0   LA_BUF  2022090800     1   LA  BUF
1   ATL_NO  2022091100     1  ATL   NO
2  CAR_CLE  2022091101     1  CAR  CLE
3   CHI_SF  2022091102     1  CHI   SF
4  CIN_PIT  2022091103     1  CIN  PIT

In [5]:
matchups_df.to_csv('data/nfl-big-data-bowl-2024/matchups.csv', index=False)